Added swoole-postgres
TechEmpower/FrameworkBenchmarks pull request #5973
Opened 2020-09-01 17:04 UTC by doubaokun

* Added swoole-postgres
* Updated the PHP version to be 7.4
* Updated Swoole postgres version to be 4.5.1

2020-09-03 07:56 UTC, joanhey requested changes

2020-09-03 07:56 UTC, joanhey commented on frameworks/PHP/swoole/benchmark_config.json
> +      "plaintext_url": "/plaintext",
Delete the tests not using db.

2020-09-03 08:33 UTC, joanhey commented on frameworks/PHP/swoole/swoole-server-postgres.php
> +        return false;
Why not add in `swoole-server.php` for both mysql and postgres?
So will be only one codebase to maintain.

2020-09-03 15:37 UTC, doubaokun commented on frameworks/PHP/swoole/benchmark_config.json
> +      "plaintext_url": "/plaintext",
Removed now.

2020-09-03 16:41 UTC, doubaokun commented
@joanhey Thanks for the review. The code is updated based on suggestion.

2020-09-04 08:27 UTC, joanhey approved these changes

2020-09-04 14:15 UTC, merged