add php framework DuckPhp
TechEmpower/FrameworkBenchmarks pull request #6090
Opened 2020-10-23 02:44 UTC by dvaknheo

first test to add  php framework DuckPhp

2020-10-23 10:16 UTC, joanhey requested changes

2020-10-23 10:16 UTC, joanhey commented on frameworks/PHP/duckphp/app/Model/WorldModel.php
> +            $sql='SELECT randomNumber FROM world WHERE id=?';
Need to request id, randomNumber
`Select id, randomNumber FROM world WHERE id=?`

2020-10-23 10:28 UTC, joanhey commented
Try to clean, and delete all unnecessary files for the benchmark.

2020-10-23 12:22 UTC, dvaknheo commented
rip the default config code . and rip some nonessessary files .may look clear .


//
frameworks/PHP/duckphp/app/Model/WorldModel.php 

I port from the base php framework code  
frameworks/PHP/php/updateraw.php  
```php
$statement = $pdo->prepare('SELECT randomNumber FROM World WHERE id=?');
$updateStatement = $pdo->prepare('UPDATE World SET randomNumber=? WHERE id=?');

// For each query, store the result set values in the response array
while ($query_count--) {
    $id = mt_rand(1, 10000);
    $statement->execute([$id]);

    // Store result in array.
    $world = ['id' => $id, 'randomNumber' => $statement->fetchColumn()];
    $world['randomNumber'] = mt_rand(1, 10000);
    $updateStatement->execute(
      [$world['randomNumber'] = mt_rand(1, 10000), $id]
    );

    $arr[] = $world;
}
```

2020-10-23 14:19 UTC, joanhey commented
The requirements changed to use id and randomNumber.
Changed in  #6072.

2020-10-25 00:57 UTC, dvaknheo commented
stable version.
and ,  can i  have  the beanchmark result. how 
without merge and just show the result to master is enough.
i guess it is better than laravel but less than ubiquity.

2020-10-26 20:43 UTC, joanhey approved these changes

2020-10-26 21:56 UTC, nbrady-techempower commented
thanks for your first contribution @dvaknheo and welcome to TFB!

@joanhey as always, thank you for your thorough reviews. It's really appreciated!

2020-10-26 21:56 UTC, merged