[PYTHON][FASTAPI] Upgrades & improvements
TechEmpower/FrameworkBenchmarks pull request #6999
Opened 2021-12-27 16:53 UTC by micaelmalta

Upgrade to Python 3.9
Upgrade all dependencies

Add nginx-unit tests
Add uvicorn tests
Add hypercorn tests
Add SQLAlchemy test

Improve PostgreSQL connexion

2021-12-28 00:47 UTC, micaelmalta commented
I believe checks are now passing 💯

2022-01-28 17:15 UTC, nbrady-techempower commented
Hi @micaelmalta - This has some conflicts from dependabot finding security vulns, can you update the requirements when you have a chance.

2022-02-08 13:40 UTC, joanhey requested changes

2022-02-08 13:40 UTC, joanhey commented on frameworks/Python/fastapi/app.py
> +    return UJSONResponse({"id": row_id, "randomNumber": number})
Here too.

2022-02-23 16:10 UTC, nbrady-techempower commented
Going to close this for now

2022-02-23 16:10 UTC, closed without merging