Add aioworkers to Python
TechEmpower/FrameworkBenchmarks pull request #7022
Opened 2022-01-15 00:30 UTC by aamalev

Adding [aioworkers](https://github.com/aioworkers) framework to the Python

2022-01-31 16:22 UTC, aamalev commented
Please approve

2022-02-08 13:32 UTC, joanhey requested changes

2022-02-08 13:32 UTC, joanhey commented on frameworks/Python/aioworkers/app.py
> +    return {"message": "Hello, world!"}
Need a JSON serializer.

https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#json-serialization

2022-02-19 23:24 UTC, aamalev commented
it works
```
Verification Summary
--------------------------------------------------------------------------------
| aioworkers
|       fortune       : PASS
|       plaintext     : PASS
|       db            : PASS
|       update        : PASS
|       json          : PASS
|       query         : PASS

```

2022-03-09 15:50 UTC, merged