Micronaut to 4.3.4 and Upgrades
TechEmpower/FrameworkBenchmarks pull request #8778
Opened 2024-02-29 17:18 UTC by timyates

- Micronaut to 4.3.4
- Micronaut Gradle plugin to latest
- Unpin micronaut-data-mongodb
- Update Gradle to 8.6

@sdelamo @dstepanov

2024-02-29 17:47 UTC, dstepanov approved these changes

2024-03-07 15:15 UTC, sdelamo approved these changes

2024-03-09 11:42 UTC, sdelamo approved these changes

2024-03-09 11:42 UTC, sdelamo commented on frameworks/Java/micronaut/gradle.properties
> +micronautVersion=4.3.4
```suggestion
micronautVersion=4.3.5
```

2024-03-22 15:48 UTC, sdelamo requested changes

2024-03-22 15:48 UTC, sdelamo commented on frameworks/Java/micronaut/buildSrc/build.gradle
> +    implementation "io.micronaut.gradle:micronaut-gradle-plugin:4.3.3"
```suggestion
    implementation "io.micronaut.gradle:micronaut-gradle-plugin:4.3.5"
```

2024-03-22 15:48 UTC, sdelamo commented on frameworks/Java/micronaut/gradle.properties
> +micronautVersion=4.3.5
```suggestion
micronautVersion=4.3.7
```

2024-03-25 15:53 UTC, timyates commented
@dstepanov I think https://github.com/TechEmpower/FrameworkBenchmarks/pull/8778/commits/2df3b66dabca568d739a26a97714afba1a2885b5 is the right solution [for the failure](https://github.com/TechEmpower/FrameworkBenchmarks/actions/runs/8392954247/job/23062492002)?

2024-04-25 13:04 UTC, sdelamo approved these changes

2024-04-25 14:26 UTC, timyates commented
@NateBrady23 Hi Nate!  Can you trigger the workflow? Hopefully this time will be green 🤞

2024-05-04 08:40 UTC, sdelamo requested changes

2024-05-04 08:40 UTC, sdelamo commented on frameworks/Java/micronaut/gradle.properties
> +micronautVersion=4.4.1
```suggestion
micronautVersion=4.4.2
```

2024-05-07 08:19 UTC, timyates commented
@NateBrady23 Sorry about this... It looks like the failure was an [issue withe the mongo tests](https://github.com/TechEmpower/FrameworkBenchmarks/actions/runs/8949311129/job/24649004953#step:9:1051) not being able to find `tf-database` on the docker network 🤔 But as far as I can tell, nothing has changed here...

Could it be a temporary docker issue that's caused the failure?

2024-05-08 17:52 UTC, NateBrady23 commented
I think the issue was on our end, but should be fixed in the main branch now. Thank you!

2024-05-08 17:52 UTC, merged