update httpserver-robaho version
TechEmpower/FrameworkBenchmarks pull request #9418
Opened 2024-11-22 17:41 UTC by robaho

Updates to JDK 23 and version 1.0.9

2025-03-17 16:47 UTC, msmith-techempower commented
Closing - feel free to open a new PR when you resolve the conflicts.

2025-03-17 16:57 UTC, robaho commented
There were no conflicts? Can you elaborate - this appears to be on the project side that wasn't able to pull the JDK23 release.

2025-03-17 18:22 UTC, robaho commented
Maven says 23 is an invalid release - but I don’t think this is the case.

2025-03-17 18:40 UTC, msmith-techempower requested changes

2025-03-17 18:40 UTC, msmith-techempower commented on frameworks/Java/httpserver-robaho/httpserver-robaho.dockerfile
> +CMD ["java", "-server", "-jar", "app.jar"]
Okay, I think I see the problem - the base image for this dockerfile is `jelastic/maven:3.9.5-openjdk-21 as maven` which suggests that openjdk is up to version 21, so it wouldn't work with a target version of 23 because it wasn't released yet.

Maybe try updating to `jelastic/maven:3.9.9-openjdk-23.0.1-almalinux-9` or similar?

2025-03-17 18:48 UTC, robaho commented on frameworks/Java/httpserver-robaho/httpserver-robaho.dockerfile
> +CMD ["java", "-server", "-jar", "app.jar"]
Thanks. Made the change. Let's see if it builds.

2025-03-19 15:45 UTC, msmith-techempower requested changes

2025-03-19 15:45 UTC, msmith-techempower commented on frameworks/Java/httpserver-robaho/httpserver-robaho.dockerfile
>  COPY src src
Below, you are still using `FROM openjdk:21-jdk-slim` instead of 23.

2025-03-19 15:54 UTC, robaho commented on frameworks/Java/httpserver-robaho/httpserver-robaho.dockerfile
>  COPY src src
I changed and comitted it. Not sure what is going on. I'll check it out.

2025-03-19 15:56 UTC, msmith-techempower commented on frameworks/Java/httpserver-robaho/httpserver-robaho.dockerfile
>  COPY src src
Sorry, you updated the `FROM jelastic/maven:3.9.5-openjdk-21 as maven` line, but you need to ALSO update line 7: `FROM openjdk:21-jdk-slim`

2025-03-19 15:56 UTC, robaho commented
The file is changed. Look at the commits. Not sure why the PR isn't showing the changes.

2025-03-19 15:59 UTC, msmith-techempower commented
I'm just not seeing that change committed.
![image](https://github.com/user-attachments/assets/d858bf52-d91a-4bd5-850c-0c5a0aa1202e)

2025-03-19 16:23 UTC, robaho commented
If you click on robaho:master you will see it is in the commits, but I don't seem to have a way to refresh this PR.

2025-03-19 16:26 UTC, msmith-techempower commented
Did a hard refresh - files changed still doesn't show it
![image](https://github.com/user-attachments/assets/e39491d9-5fda-4b9a-9ffd-32ac906476ce)

2025-03-19 16:40 UTC, robaho commented
so sorry, I was only review the first line, which is where this started. I apologize for wasting your time.

2025-03-19 16:48 UTC, robaho commented
I updated it, and it is still failing.

2025-03-19 21:16 UTC, msmith-techempower commented
It's because you updated the `pom.xml` to specify version 23, but you didn't update [the other dockerfile](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/httpserver-robaho/httpserver-robaho-postgres.dockerfile) to have the same changes.

2025-03-24 20:17 UTC, msmith-techempower approved these changes

2025-03-24 20:17 UTC, merged